version: '3.9'

services:
  node-app:
    platform: linux/amd64
    container_name: Task-5.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/check-health || exit 1"]
      interval: 20s
      timeout: 12s
      retries: 3
      start_period: 20s
    restart: on-failure
